# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_f', models.IntegerField()),
                ('from_f', models.IntegerField()),
                ('status', models.IntegerField()),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('uid', models.IntegerField()),
                ('from_user', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_fname', models.CharField(blank=True, max_length=40, null=True)),
                ('user_lname', models.CharField(blank=True, max_length=40, null=True)),
                ('user_email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=255)),
                ('joining_date', models.DateTimeField()),
                ('user_dob', models.DateField()),
                ('user_country', models.CharField(blank=True, max_length=3, null=True)),
                ('user_gender', models.CharField(max_length=1)),
                ('user_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('user_about', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'tbl_users',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
    ]
