# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0002_auto_20170121_1013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='myWebsite_article',
        ),
    ]
