# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0003_auto_20170121_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('likes', models.IntegerField()),
            ],
            options={
                'db_table': 'myWebsite_article',
                'managed': False,
            },
        ),
    ]
