# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0004_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': False, 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'managed': False, 'verbose_name': 'Requests', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
