# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0005_auto_20170121_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True, 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
    ]
